//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ObjectModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section,d (in.),bf (in.),tf (in.),tw (in.),k (in.),Area (in.^2),Ix (in.^4),Iy (in.^4),Sx (in.^3),Sy (in.^3),Zx (in.^3),Zy (in.^3),Rx (in.),Ry (in.),J (in.^4)
        ///W44X335,44,15.9,1.77,1.03,2.56,98.5,31100,1200,1410,150,1620,236,17.8,3.49,74.7
        ///W44X290,43.6,15.8,1.58,0.865,2.36,85.4,27000,1040,1240,132,1410,205,17.8,3.49,50.9
        ///W44X262,43.3,15.8,1.42,0.785,2.2,77.2,24100,923,1110,117,1270,182,17.7,3.47,37.3
        ///W44X230,42.9,15.8,1.22,0.71,2.01,67.8,20800,796,971,101,1100,157,17.5,3.43,24.9
        ///W40X655,43.6,16.9,3.54,1. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WShape {
            get {
                return ResourceManager.GetString("WShape", resourceCulture);
            }
        }
    }
}
